// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvtpytqjavofrpaimksv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dHB5dHFqYXZvZnJwYWlta3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODMzMzUsImV4cCI6MjA3MTY1OTMzNX0.ZjopC6yzHoJeHCL6O4ir1W5QYv8NTLSlmSdNv6EhGoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});